apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: atw1a/dbapp
        ports:
        - containerPort: 3306
      volumes:
      - name: project-sql
        configMap:
          name: project-sql

