version: '3'
services:
  db:
    image: dbapp:latest
    ports:
      - "3306:3306"
    volumes:
      - "./project.sql:/docker-entrypoint-initdb.d/mydatabase.sql"
  web:
    image: webapp:latest
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
